In [90]:
from pathlib import Path
import os
import pandas as pd

In [91]:
path = Path('../data')

In [92]:
os.listdir(path)

['train.csv',
 'test.csv',
 'sample_submission.csv',
 'train_annotation',
 'train_tracking',
 'test_tracking']

In [93]:
df = pd.read_csv(path/'train.csv')
df.shape

(8790, 38)

In [94]:
df.columns

Index(['lab_id', 'video_id', 'mouse1_strain', 'mouse1_color', 'mouse1_sex',
       'mouse1_id', 'mouse1_age', 'mouse1_condition', 'mouse2_strain',
       'mouse2_color', 'mouse2_sex', 'mouse2_id', 'mouse2_age',
       'mouse2_condition', 'mouse3_strain', 'mouse3_color', 'mouse3_sex',
       'mouse3_id', 'mouse3_age', 'mouse3_condition', 'mouse4_strain',
       'mouse4_color', 'mouse4_sex', 'mouse4_id', 'mouse4_age',
       'mouse4_condition', 'frames_per_second', 'video_duration_sec',
       'pix_per_cm_approx', 'video_width_pix', 'video_height_pix',
       'arena_width_cm', 'arena_height_cm', 'arena_shape', 'arena_type',
       'body_parts_tracked', 'behaviors_labeled', 'tracking_method'],
      dtype='object')

In [166]:
df.head()

,lab_id,video_id,mouse1_strain,mouse1_color,mouse1_sex,mouse1_id,mouse1_age,mouse1_condition,mouse2_strain,mouse2_color,...,pix_per_cm_approx,video_width_pix,video_height_pix,arena_width_cm,arena_height_cm,arena_shape,arena_type,body_parts_tracked,behaviors_labeled,tracking_method
0,AdaptableSnail,44566106,CD-1 (ICR),white,male,10.0,8-12 weeks,wireless device,CD-1 (ICR),white,...,16.0,1228,1068,60.0,60.0,square,familiar,"[""body_center"", ""ear_left"", ""ear_right"", ""head...","[""mouse1,mouse2,approach"", ""mouse1,mouse2,atta...",DeepLabCut
1,AdaptableSnail,143861384,CD-1 (ICR),white,male,3.0,8-12 weeks,NaN,CD-1 (ICR),white,...,9.7,968,608,60.0,60.0,square,familiar,"[""body_center"", ""ear_left"", ""ear_right"", ""late...","[""mouse1,mouse2,approach"", ""mouse1,mouse2,atta...",DeepLabCut
2,AdaptableSnail,209576908,CD-1 (ICR),white,male,7.0,8-12 weeks,NaN,CD-1 (ICR),white,...,16.0,1266,1100,60.0,60.0,square,familiar,"[""body_center"", ""ear_left"", ""ear_right"", ""late...","[""mouse1,mouse2,approach"", ""mouse1,mouse2,atta...",DeepLabCut
3,AdaptableSnail,278643799,CD-1 (ICR),white,male,11.0,8-12 weeks,wireless device,CD-1 (ICR),white,...,16.0,1224,1100,60.0,60.0,square,familiar,"[""body_center"", ""ear_left"", ""ear_right"", ""head...","[""mouse1,mouse2,approach"", ""mouse1,mouse2,atta...",DeepLabCut
4,AdaptableSnail,351967631,CD-1 (ICR),white,male,14.0,8-12 weeks,NaN,CD-1 (ICR),white,...,16.0,1204,1068,60.0,60.0,square,familiar,"[""body_center"", ""ear_left"", ""ear_right"", ""late...","[""mouse1,mouse2,approach"", ""mouse1,mouse2,atta...",DeepLabCut

In [119]:
df[['frames_per_second', 'pix_per_cm_approx', 'video_width_pix', 'video_height_pix']].head()

   frames_per_second  pix_per_cm_approx  video_width_pix  video_height_pix
0               30.0               16.0             1228              1068
1               25.0                9.7              968               608
2               30.0               16.0             1266              1100
3               30.0               16.0             1224              1100
4               30.0               16.0             1204              1068

In [96]:
# all the videos are unique
df['video_id'].nunique()

8790

In [97]:
# colors of mouse
print(df['mouse1_color'].unique())
print(df['mouse2_color'].unique())
print(df['mouse3_color'].unique())
print(df['mouse4_color'].unique())

['white' 'black' 'brown' 'black and tan']
['white' 'black' 'brown' 'black and tan']
['white' nan 'black and tan' 'black']
['white' nan]

In [98]:
df['mouse1_age'].unique()

array(['8-12 weeks', '7-14 weeks', nan, '17-21 weeks', '8-26 weeks',
       '10-20 weeks', '> 40 weeks', '12 weeks', '8 weeks'], dtype=object)

In [99]:
df['tracking_method'].unique()

array(['DeepLabCut', 'MARS', 'SLEAP', 'custom HRnet'], dtype=object)

In [142]:
len(df['behaviors_labeled'][0])

1868

# Analysis 2

In [121]:
idx = 0
lab_id = df.iloc[idx]['lab_id']
video_id = df.iloc[idx]['video_id']

file_path = os.path.join(path, 'train_tracking', lab_id, str(video_id)+'.parquet')
temp = pd.read_parquet(file_path)

print(temp.shape)
print(temp.bodypart.nunique())
print(temp.bodypart.unique())
temp.head()

(1087658, 5)
18
['body_center' 'ear_right' 'headpiece_bottomfrontright'
 'headpiece_topbackright' 'headpiece_topfrontleft'
 'headpiece_topfrontright' 'lateral_left' 'lateral_right' 'tail_base'
 'tail_midpoint' 'tail_tip' 'headpiece_bottombackleft'
 'headpiece_bottombackright' 'headpiece_bottomfrontleft'
 'headpiece_topbackleft' 'nose' 'ear_left' 'neck']

   video_frame  mouse_id                    bodypart            x           y
0            0         1                 body_center  1161.543945  523.112976
1            0         1                   ear_right  1146.305054  587.619995
2            0         1  headpiece_bottomfrontright  1163.192017  588.580017
3            0         1      headpiece_topbackright  1192.211060  558.434998
4            0         1      headpiece_topfrontleft  1191.343994  620.625977

In [128]:
print(temp.video_frame.nunique())
print(temp.video_frame.nunique()/30) # 30 frame per second

18451
615.0333333333333

In [154]:
frane_no = 20
from collections import Counter
print(len(temp.loc[temp['video_frame']==frane_no]['bodypart'].to_list()))
print(Counter(temp.loc[temp['video_frame']==frane_no]['bodypart'].to_list()))
temp.loc[temp['video_frame']==frane_no]

58
Counter({'body_center': 4, 'headpiece_bottombackright': 4, 'headpiece_bottomfrontright': 4, 'headpiece_topbackright': 4, 'headpiece_topfrontleft': 4, 'headpiece_topfrontright': 4, 'lateral_left': 4, 'tail_base': 4, 'tail_midpoint': 4, 'ear_right': 3, 'lateral_right': 3, 'tail_tip': 3, 'ear_left': 3, 'headpiece_bottombackleft': 3, 'headpiece_topbackleft': 3, 'nose': 2, 'headpiece_bottomfrontleft': 2})

,video_frame,mouse_id,bodypart,x,y
1102,20,1,body_center,1167.578003,789.294006
1103,20,1,ear_right,1146.162964,846.463989
1104,20,1,headpiece_bottombackright,1195.678955,821.794006
1105,20,1,headpiece_bottomfrontright,1171.620972,867.120972
1106,20,1,headpiece_topbackright,1193.774048,829.713989
1107,20,1,headpiece_topfrontleft,1197.042969,881.390015
1108,20,1,headpiece_topfrontright,1168.800049,863.802979
1109,20,1,lateral_left,1195.182007,772.499023
1110,20,1,lateral_right,1138.048950,795.398987
1111,20,1,nose,1179.150024,876.166016
1112,20,1,tail_base,1158.305054,745.439026
1113,20,1,tail_midpoint,1145.589966,673.486023
1114,20,1,tail_tip,1145.166016,614.840027
1115,20,2,body_center,346.226013,482.196014
1116,20,2,ear_left,348.098999,572.794983
1117,20,2,ear_right,328.541992,521.533997
1118,20,2,headpiece_bottombackleft,404.666992,532.825989
1119,20,2,headpiece_bottombackright,386.786987,514.036011
1120,20,2,headpiece_bottomfrontleft,353.830994,561.581970
1121,20,2,headpiece_bottomfrontright,344.153992,535.434998
1122,20,2,headpiece_topbackleft,400.324005,540.604980
1123,20,2,headpiece_topbackright,390.350006,513.075989
1124,20,2,headpiece_topfrontleft,369.109985,564.164978
1125,20,2,headpiece_topfrontright,357.710999,534.559998
1126,20,2,lateral_left,371.450012,482.263000
1127,20,2,lateral_right,318.587006,482.803009
1128,20,2,nose,327.987000,571.518982
1129,20,2,tail_base,352.442993,445.753998
1130,20,2,tail_midpoint,355.408997,436.415985
1131,20,3,body_center,1122.844971,506.308014
1132,20,3,ear_left,1116.255005,555.866028
1133,20,3,ear_right,1071.826050,532.841980
1134,20,3,headpiece_bottombackleft,1127.235962,571.109985
1135,20,3,headpiece_bottombackright,1108.666992,541.562988
1136,20,3,headpiece_bottomfrontright,1064.026978,553.846008
1137,20,3,headpiece_topbackleft,1118.402954,584.651978
1138,20,3,headpiece_topbackright,1102.848999,556.333008
1139,20,3,headpiece_topfrontleft,1071.223022,591.625000
1140,20,3,headpiece_topfrontright,1060.578979,560.046997
1141,20,3,lateral_left,1150.068970,507.170013
1142,20,3,lateral_right,1106.786011,481.407013
1143,20,3,tail_base,1144.756958,455.829987
1144,20,3,tail_midpoint,1169.645020,387.875000
1145,20,3,tail_tip,1158.645020,320.971008
1146,20,4,body_center,415.110992,489.407013
1147,20,4,ear_left,444.862000,524.218018
1148,20,4,headpiece_bottombackleft,444.187012,530.294983
1149,20,4,headpiece_bottombackright,452.222992,531.203003
1150,20,4,headpiece_bottomfrontleft,443.404999,531.153015
1151,20,4,headpiece_bottomfrontright,411.699005,556.643982
1152,20,4,headpiece_topbackleft,473.131012,564.741028
1153,20,4,headpiece_topbackright,457.752991,539.739990
1154,20,4,headpiece_topfrontleft,431.868011,588.572998
1155,20,4,headpiece_topfrontright,415.773010,562.049011
1156,20,4,lateral_left,437.488007,476.299011
1157,20,4,tail_base,392.721008,445.259003
1158,20,4,tail_midpoint,356.022003,380.273987
1159,20,4,tail_tip,325.709991,322.213013

In [156]:
temp.tail()

         video_frame  mouse_id       bodypart           x           y
1087653        18450         4   lateral_left  250.681000  646.434021
1087654        18450         4  lateral_right  297.471985  679.210022
1087655        18450         4      tail_base  265.600006  688.062012
1087656        18450         4  tail_midpoint  263.371002  748.155029
1087657        18450         4       tail_tip  531.512024  489.929993

## Annotations

In [165]:
idx = 0
lab_id = df.iloc[idx]['lab_id']
video_id = df.iloc[idx]['video_id']

file_path = os.path.join(path, 'train_annotation', lab_id, str(video_id)+'.parquet')
label = pd.read_parquet(file_path)
print(label.shape)
label.head()

(342, 5)

   agent_id  target_id action  start_frame  stop_frame
0         2          2   rear            4         139
1         4          2  avoid           13          52
2         4          4   rear          121         172
3         3          3   rear          156         213
4         4          4   rear          208         261